### ISSUE TITLE
`target_arch` usage in macros is useless

### ISSUE THREAD

**Issue by RinLovesYou** [WarrenHood/proxygen#1]
[Responsible Line](https://github.com/WarrenHood/proxygen/blob/main/proxygen-macros/src/lib.rs#L109)

Hiya, trying to cross-compile from linux here. Macros (stupidly) only run on your host. This means `target_arch` == `host_arch`.
Quick fix would be having the `cfg!` be emitted in the token stream. I'll probably do a PR for this in a bit.

**Comment by WarrenHood** [comment]
Hi! That makes sense. I wasn't aware that proc macros used the host arch as the target arch :/

Would really appreciate a PR with the fix whenever you get a chance. Thanks!

**Comment by RinLovesYou** [comment]
It really is confusing. Cross compilation has always been a little painful, but we must support the windows users! 😅

Getting started on this now.

**Comment by WarrenHood** [comment]
Awesome! No rush, I'll only be able to review it when I wake up tomorrow
